domains:
    build: ./domains
    volumes:
        - /etc/nginx/conf.d/

data:
    build: ./data
    volumes:
        - /vagrant/application/:/srv/http/

postgresql:
    build: ./postgresql
    expose:
        - "5432"
    ports:
        - "5432:5432"
phpcli:
    build: ./phpcli
    volumes_from:
        - data
    links:
        - postgresql

phpfpm:
    build: ./phpfpm
    volumes_from:
        - data
    expose:
        - "9000"
    ports:
        - "9000:9000"
    links:
        - postgresql

nginx:
    build: ./nginx
    volumes_from:
        - data
        - domains
    expose:
        - "80"
    ports:
        - "80:80"
    links:
        - phpfpm
