FROM php:cli

MAINTAINER Taylor Silenzio <tsilenzio@gmail.com>

# Add the config files
# ADD conf.d/* /tmp/

# Install configuration files
# RUN mv /tmp/php.ini /usr/local/etc/php/php.ini

# Add persistant volume
VOLUME ["/srv/http"]
